spec:
    replicas: 3
    template:
      metadata:
        labels:
          app: d8-example
    spec:
      containers:
      - name: d8-example
        image: gcr.io/$GCLOUD_PROJECT/d8-example
        imagePullPolicy: Always
        env:
        - name: DRUPAL_DB_NAME
          value: d8_example
        ports:
        - name: http-server
          containerPort: 8080
      - name: cloudsql-proxy
        image: b.gcr.io/cloudsql-docker/gce-proxy:1.05
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                  "-instances=focal-lens-154919:us-central1:drupal8-example=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-oauth-credentials
          mountPath: /secrets/cloudsql
          readOnly: true
        - name: ssl-certs
          mountPath: /etc/ssl/certs
        - name: cloudsql
          mountPath: /cloudsql
        volumes:
        - name: cloudsql-oauth-credentials
          secret:
            secretName: cloudsql-oauth-credentials
        - name: ssl-certs
          secret:
            secretName: /etc/ssl/certs
