apiVersion: v1
kind: Service
metadata:
    name:  d8-k8
    labels:
        app: d8-example
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: http-server
    selector:
        app: d8-example
